apiVersion: v1
kind: Namespace
metadata:
  name: new

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: new
spec:
  hard:
    requests.cpu: "250m"  
    limits.cpu: "500m"       
    #requests.memory: "250Mi"
    #limits.memory: "500Mi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-restriction
  namespace: new
spec: 
  replicas: 1
  selector: 
    matchLabels:
      cpu: v1
  template:
    metadata: 
      labels:
        cpu: v1
    spec:
      containers:
        - name: cpu
          image: ubuntu:latest
          command: ['sh','-c','while true; do date & sleep 2; done']
          resources:
            limits:
              cpu: 60m
    #          memory: 200Mi
            requests:
              cpu: 50m
   #           memory: 100Mi
